services:
  - type: web
    name: shinwa
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_API_KEY # Manus組み込みAI用
        sync: true
      - key: OPENAI_BASE_URL # Manus組み込みAI用
        sync: true