services:
  - type: web
    name: shinwa
    runtime: node
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXT_PUBLIC_OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ANTHROPIC_API_KEY
        sync: false
      - key: NEXT_PUBLIC_OPENAI_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_ANTHROPIC_BASE_URL
        sync: false