name: Rotate Claude OAuth Tokens

on:
  schedule:
    # ⇒ 毎週月曜 AM-3:00（JST）に実行。失効 30 日より十分手前で更新
    - cron:  '0 18 * * 0'
  workflow_dispatch:   # 必要に応じて手動実行

permissions:
  contents: read       # リポジトリの public-key 取得に必要
  # ※ secrets 書き換えは PAT 権限で行うのでここでは不要

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get -y update && sudo apt-get -y install jq

      - name: Refresh via Anthropic OAuth
        id: refresh
        env:
          REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
        run: |
          set -e
          resp=$(curl -sS -X POST https://api.anthropic.com/oauth/token \
            -d grant_type=refresh_token \
            -d refresh_token="$REFRESH_TOKEN" \
            -d client_id=gh-action \
            -d client_secret=unused)

          new_access=$(echo "$resp" | jq -r .access_token)
          new_refresh=$(echo "$resp" | jq -r .refresh_token)
          new_expires=$(echo "$resp" | jq -r '.expires_at // (now + 1800)')

          if [[ -z "$new_access" || -z "$new_refresh" ]]; then
            echo "❌ Failed to parse tokens"; echo "$resp"; exit 1
          fi
          echo "::add-mask::$new_access"
          echo "::add-mask::$new_refresh"
          echo "access=$new_access"   >> "$GITHUB_OUTPUT"
          echo "refresh=$new_refresh" >> "$GITHUB_OUTPUT"
          echo "expires=$new_expires" >> "$GITHUB_OUTPUT"

      - name: Update repo secrets (gh CLI)
        # secrets 書き換えには PAT (repo, actions:write) が必要
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "${{ steps.refresh.outputs.access  }}" | gh secret set CLAUDE_ACCESS_TOKEN  -b-
          echo "${{ steps.refresh.outputs.refresh }}" | gh secret set CLAUDE_REFRESH_TOKEN -b-
          echo "${{ steps.refresh.outputs.expires }}" | gh secret set CLAUDE_EXPIRES_AT    -b-
          echo "✅ GitHub Secrets updated"

      - name: Notify (optional)
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"text":"Claude token rotation failed for repo '${{ github.repository }}'."}' \
            "$SLACK_WEBHOOK"
